#include "gpio.h"

void GPIO_Init(void){
	
	RCC->AHB2ENR|=(RCC_AHB2ENR_GPIOAEN|RCC_AHB2ENR_GPIOBEN|RCC_AHB2ENR_GPIOCEN|RCC_AHB2ENR_GPIOGEN);
	
//	GPIOA->MODER=0x28000000;
//	GPIOA->MODER|=(GPIO_MODE_OUTPUT<<(5<<1));
//	GPIOA->OTYPER|=(GPIO_OUTPUT_PUSHPULL<<5);
//	GPIOA->OSPEEDR|=(GPIO_SPEED_FREQ_LOW <<(5<<1));
//	GPIOA->PUPDR|=(GPIO_PULL_NO<<(5<<1));
//	GPIOA->BSRR=0;
	
	GPIOC->MODER&=~GPIO_MODER_MODE6_Msk;
	GPIOC->MODER|=(GPIO_MODE_OUTPUT<<(6<<1));
	GPIOC->OTYPER|=(GPIO_OUTPUT_PUSHPULL<<6);
	GPIOC->OSPEEDR|=(GPIO_SPEED_FREQ_LOW <<(6<<1));
	GPIOC->PUPDR|=(GPIO_PULL_NO<<(6<<1));
	GPIOC->BSRR=0;
}
